name: Sign html files and Deploy

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  signing and deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install GPG agent and put password to key into file
        run: |
          sudo apt-get install gnupg-agent

      - name: Import GPG Key
        run: |
          gpg --import <(echo $GPG_SIGNING_KEY)
        env:
          GPG_SIGNING_KEY: secrets.GPG_KEY

      - name: Everything about signing files
        run: |
          git clone https://github.com/tasn/webext-signed-pages.git
          cd webext-signed-pages
          npm install
          cp ../.github/workflows/page-signer-edited.js ./
          cd ..
          chmod 700 ./webext-signed-pages/page-signer-edited.js
          gpg --export -a henshouse > pub.key
          node ./webext-signed-pages/page-signer-edited.js index.unsigned.html index.html
          node ./webext-signed-pages/page-signer-edited.js download.unsigned.html download.html
          node ./webext-signed-pages/page-signer-edited.js faq.unsigned.html faq.html
          node ./webext-signed-pages/page-signer-edited.js signed.unsigned.html signed.html
          node ./webext-signed-pages/page-signer-edited.js source.unsigned.html source.html
          rm -r webext-signed-pages
        env:
          GPG_SIGNING_KEY: secrets.GPG_PASSPHRASE
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .