name: Sign and publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install GPG agent and put password to key into file
        run: sudo apt-get install gnupg-agent && echo "$GPG_PASSPHRASE" > ./passcode.txt
        env:
          GPG_SIGNING_KEY: secrets.GPG_PASSPHRASE

      - name: Import GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: secrets.GPG_KEY

      - name: everything about singing key
        run: |
          git clone https://github.com/tasn/webext-signed-pages.git
          cd webext-signed-pages
          npm install
          wget https://raw.githubusercontent.com/henshouse/henshouse.github.io/main/.github/workflows/page-signer-edited.js 
          cd ..
          chmod 700 ./webext-signed-pages/page-signer-edited.js
          node ./webext-signed-pages/page-signer-edited.js index.unsigned.html index.html

      - name: Deploy to GitHub Pages
        run: |
          rm -r webext-signed-pages.git
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout --orphan gh-pages
          git rm --cached -r .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages
