name: Sign and publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install GPG agent
        run: sudo apt-get install gnupg-agent

      - name: Import GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: secrets.GPG_KEY

      - name: clone Signed Pages git, Install dependencies and sing index.html
        run: git clone https://github.com/tasn/webext-signed-pages.git && cd webext-signed-pages && npm install && wget https://raw.githubusercontent.com/henshouse/henshouse.github.io/main/.github/workflows/page-signer.bash && cd .. && ./webext-signed-pages/page-signer.bash index.unsigned.html index.html

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout --orphan gh-pages
          git rm --cached -r .
          cp -a build/. .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages
