name: Sing html files for Signed Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install GPG agent and put password to key into file
        run: sudo apt-get install gnupg-agent && echo "$GPG_SIGNING_KEY" > ./passcode.txt
        env:
          GPG_SIGNING_KEY: secrets.GPG_PASSPHRASE

      - name: Import GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        env:
          GPG_SIGNING_KEY: secrets.GPG_KEY

      - name: Everything about singing files
        run: |
          git clone https://github.com/tasn/webext-signed-pages.git
          cd webext-signed-pages
          npm install
          cp ../.github/workflows/page-signer-edited.js ./
          cd ..
          chmod 700 ./webext-signed-pages/page-signer-edited.js
          node ./webext-signed-pages/page-signer-edited.js index.unsigned.html index.html
          rm passcode.txt
          rm -r webext-signed-pages

      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: .
          branch: main
          token: ${{ secrets.ACCESS_TOKEN }}